### PR TITLE
added support for translating multiple words.

### PR DESCRIPTION
**Pull request by definitelycarter**
A really fun exercise!  My first couple of attempts ended with build failures due to typos.  Finally my test passed and I fetched me and the gopher some coffee.

### CODE REVIEW

**Comment by matryer** [comment]
Great stuff - Did you see this one?  What do you think?  https://github.com/stretchr/piglatin/pull/1

**Comment by definitelycarter** [comment]
I liked his implementation as it left the original `Translate` implementation intact.  Some downsides to his approach:
- It doesn't change that `Translate` is broken when using multiple words.
- `Translate` still needs to be modified to return an error if multiple words are passed in.
- `TestTranslateMultiple` doesn't utilize the existing `translateTests`.
- `TestTranslateMultiple` and `TestTranslate` tests the same scenario (the former is batched).  I believe `TestTranslateMultiple` is redundant.

The downside to my approach is that it required more modifications to my `Translate` implementation. I was worried of this because the blog post stated that I should "Write the minimum amount of code you can to make the test pass". The upside is that the test didn't have to change and all we had to do was add our scenario to our `translateTests`.  I followed the requirement that "the `Translate` function should support multiple words" stated in the blog post.

Thanks!

**Comment by matryer** [comment]
You guys all win :beers: - somehow... Tweet me @matryer and we'll figure it out.

**Comment by definitelycarter** [comment]
Thanks!

**Pull request closed without merging**
